### ISSUE TITLE
UDP port stays open in macOS

### ISSUE THREAD

**Issue by hmijail** [status-im/nimbus-eth2#2048] opened 2020-11-20 05:39 UTC
**Describe the bug**
Somehow, nimbus-eth2 leaves open an UDP port even after dead.

**To Reproduce**
1. Platform details (OS, architecture): 'macOS 10.15.7 (19H15)'
2. Branch/commit used: 'master, 771c1d092aaf5eac062414feafc59c7a1ef121b2'
3. Commands being executed: 
`./build/nimbus_beacon_node_spec_0_12_3 --network=medalla -d=xxxxx --web3-url=xxxx --nat=extip:xx.xx.xx.xx --tcp-port=10001 --udp-port=10001 --in-process-validators --rpc --metrics`
4. Relevant log lines: 
`FAT 2020-11-20 13:45:10.123+10:00 Failed to start discovery service. UDP port may be already in use topics="networking" tid=4761122 file=eth2_network.nim:987`

**Additional context**
First I ran nimbus on ports 10000, bot UDP and TCP. It started syncing. I stopped it with ^C, and after a while I repeated the command to start it. It failed with the given line `Failed to start discovery service. UDP port may be already in use`.

This kept happening for about 30 minutes, so any socket timeout should have kicked in.
I tried deleting the data directory, didn't help.
Finally I changed both ports to 10001, and then it started.
But then I again used ^C, tried to restart, and again it won't.

As far as I can tell, nothing is using those ports, but `netstat` reports them still open.
Looks like it's an OS-level problem, but until now only nimbus has triggered it, so maybe you can do something to avoid it? See https://stackoverflow.com/questions/40512274/release-udp-port-used-by-dead-process-on-os-x

```
$ netstat -an -f inet | grep 1000
udp4  121712      0  *.10001                *.*
udp4  319172      0  *.10000                *.*
$
```
```
$ sudo lsof -nPi | grep 1000
$
```

**Comment by kdeme** [comment] 2020-11-30 17:13
Thanks for your detailed report.

It is strange that you are hitting this for a UDP socket. I've never seen that but it seems macOS specific. It might be because the socket doesn't get closed in time, but normally one would expect the OS to (eventually) clean-up. 

Within Nimbus, the UDP socket does usually get closed on ^C but there is a timeout of 5 seconds, so perhaps that timeout gets hit: https://github.com/status-im/nimbus-eth2/blob/8327240458c5d56d9cdaedb4a2ecac481c993da6/beacon_chain/eth2_network.nim#L1167 

I'll see if I can set something up to reproduce this myself.

In the meanwhile, if you have the possibility to rebuild the code yourself, you could try to change that timeout mentioned above, to a much higher value, as a test.

Additionally, you could also try to build and test with this branch: https://github.com/status-im/nimbus-eth2/tree/disc-reuseaddr. It sets the `SO_REUSEADDR` flag which should hopefully allow it to reuse the socket. Don't use this branch though for anything else but testing.

**Comment by hmijail** [comment] 2020-11-30 23:06
I still didn't restart my computer since I reported the issue, so I just ran the netstat line again, and the ports are **still** open (LOL!). So I really don't think changing any timeout in the code is going to help :).

**Comment by kdeme** [comment] 2020-12-02 20:47
To be clear, this is about the time that we wait to properly close the socket on graceful shutdown. But sure, it can be that this is not the problem.

**Comment by hmijail** [comment] 2020-12-03 00:36
FWIW, I submitted a bug report to Apple and to OpenRadar: http://www.openradar.me/radar?id=4997125951717376

**Comment by mratsim** [comment] 2022-03-09 10:42
I don't think we can do anything on our side regarding this except wait for Apple so closing on our end.

**Closed by mratsim** 2022-03-09 10:42 UTC
