### ISSUE TITLE
Could not run mingw32-make update on Windows anymore.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nimbus-eth2#2180] opened 2020-12-14 03:23 UTC
My CPU information is here https://gist.github.com/cheatfate/f124805d86387e44e41b648dd9953874
```
gcc.exe (Rev2, Built by MSYS2 project) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ mingw32-make V=1 update
which gcc &>/dev/null || { echo "C compiler (gcc) not installed. Aborting."; exit 1; }
git submodule foreach --quiet 'git ls-files --exclude-standard --recurse-submodules -z -- ":!:.*" | xargs -0 rm -rf'
git submodule update --init --recursive || true
# changing URLs in a submodule's submodule means we have to sync and update twice
git submodule sync --quiet --recursive
git submodule update --init --recursive
git submodule foreach --quiet --recursive 'git reset --quiet --hard'
find . -type d -name nimcache -print0 | xargs -0 rm -rf
rm -rf vendor/.nimble
"C:/system/msys64_full/mingw64/bin/mingw32-make.exe" --no-print-directory deps
which gcc &>/dev/null || { echo "C compiler (gcc) not installed. Aborting."; exit 1; }
mkdir -p vendor/.nimble/pkgs
NIMBLE_DIR="C:/Projects/nim-beacon-chain/vendor/.nimble" PWD_CMD="pwd -W" \
        git submodule foreach --recursive --quiet 'C:/Projects/nim-beacon-chain/vendor/nimbus-build-system/scripts/create_nimble_link.sh "$sm_path"'
[ -e vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc/libminiupnpc.a ] || \
        "C:/system/msys64_full/mingw64/bin/mingw32-make.exe" -C vendor/nim-nat-traversal/vendor/miniupnp/miniupnpc -f Makefile.mingw CC=gcc libminiupnpc.a
"C:/system/msys64_full/mingw64/bin/mingw32-make.exe" -C vendor/nim-nat-traversal/vendor/libnatpmp-upstream CC=gcc CFLAGS="-Wall -Os -DWIN32 -DNATPMP_STATICLIB -DENABLE_STRNATPMPERR -DNATPMP_MAX_RETRIES=4 " libnatpmp.a
gcc -Wall -Os -DWIN32 -DNATPMP_STATICLIB -DENABLE_STRNATPMPERR -DNATPMP_MAX_RETRIES=4    -c -o natpmp.o natpmp.c
In file included from C:/system/msys64_full/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/include/immintrin.h:55,
                 from C:/system/msys64_full/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/include/x86intrin.h:32,
                 from C:/system/msys64_full/mingw64/x86_64-w64-mingw32/include/winnt.h:1554,
                 from C:/system/msys64_full/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/system/msys64_full/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/system/msys64_full/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/system/msys64_full/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from natpmp.c:39:
C:/system/msys64_full/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/include/avx512fintrin.h: In function '_mm512_mask_reduce_mul_ps':
C:/system/msys64_full/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/include/avx512fintrin.h:15958:3: internal compiler error: Segmentation fault
15958 |   __A = _mm512_mask_mov_ps (_mm512_set1_ps (1.0f), __U, __A);
      |   ^~~
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
mingw32-make[2]: *** [<builtin>: natpmp.o] Error 1
mingw32-make[1]: *** [vendor/nimbus-build-system/makefiles/targets.mk:106: libnatpmp.a] Error 2
mingw32-make: *** [vendor/nimbus-build-system/makefiles/targets.mk:81: update-common] Error 2
```

**Comment by stefantalpalaru** [comment] 2020-12-14 12:08
Here's your problem: https://github.com/msys2/MINGW-packages/issues/6674#issuecomment-685060259

**Comment by cheatfate** [comment] 2020-12-14 12:18
Maybe this is GCC problem of course, but this only means we should workaround it, because this problem appears recently. I was able to compile project two weeks ago.

**Comment by stefantalpalaru** [comment] 2020-12-14 15:15
It's an MSYS2 problem and we don't support MSYS2. That said, it's not usually feasible to work around a buggy compiler.

Try upgrading your packages. I see they talk about bootstrapping GCC with various dependency versions in that issue thread. Are all packages compiled from source? Can you try a fresh install?

**Comment by cheatfate** [comment] 2021-03-26 13:21
The only way to avoid it with current options inside `config.nims` is to use 
```gcc.exe (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0```

**Comment by cheatfate** [comment] 2021-03-26 13:27
Also this issue could be mitigated if you comment
https://github.com/status-im/nimbus-eth2/blob/stable/config.nims#L62-L63

**Comment by jakubgs** [comment] 2021-05-11 15:59
I hit my head against this in https://github.com/status-im/infra-ci/issues/32 and my "solution" was to downgrade Git version from `2.31.1.windows.1` to `2.28.0.windows.1`, which fixed the `avx512fintrin.h:15958:3: internal compiler error: Segmentation fault` error for me.

Since the issue was caused by ["messed up libgmp"](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97124#c7) and Git comes with it's own:
```
/c/ProgramData/scoop/apps/git/2.31.1.windows.1/mingw64/bin/libgmp-10.dll
/c/ProgramData/scoop/apps/git/2.31.1.windows.1/mingw64/libexec/git-core/libgmp-10.dll
```

**Comment by mratsim** [comment] 2022-03-09 10:50
Issue fixed on our fleet and we have Windows CI (and windows users). Closing.

**Closed by mratsim** 2022-03-09 10:50 UTC

**Comment by jakubgs** [comment] 2022-03-09 15:30
It's only fixed because I pinned to old Git verision:
```
admin@windows-01 MINGW64 ~
$ grep version /c/ProgramData/scoop/apps/git/current/manifest.json | head -n1
    "version": "2.28.0.windows.1",
```
I have no idea if this is still an issue on `2.31.1.windows.1` newer than that.
